// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2kmZ7zf9_-XhI4XqsX7jXlKkHdtS5Vo',
    appId: '1:792474175652:web:b4ec3f356edff8dec9fe31',
    messagingSenderId: '792474175652',
    projectId: 'gemini-ee839',
    authDomain: 'gemini-ee839.firebaseapp.com',
    storageBucket: 'gemini-ee839.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZQ1cL-Vomm1HGqAVtwq-HrmW5TkEQho',
    appId: '1:792474175652:android:e8bc72b8d7686177c9fe31',
    messagingSenderId: '792474175652',
    projectId: 'gemini-ee839',
    storageBucket: 'gemini-ee839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUDRuKUAq4jaGcgkpGoMaofzjfPK67oGs',
    appId: '1:792474175652:ios:cbffb67c7ba770f2c9fe31',
    messagingSenderId: '792474175652',
    projectId: 'gemini-ee839',
    storageBucket: 'gemini-ee839.appspot.com',
    iosBundleId: 'com.example.googleGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUDRuKUAq4jaGcgkpGoMaofzjfPK67oGs',
    appId: '1:792474175652:ios:cbffb67c7ba770f2c9fe31',
    messagingSenderId: '792474175652',
    projectId: 'gemini-ee839',
    storageBucket: 'gemini-ee839.appspot.com',
    iosBundleId: 'com.example.googleGemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2kmZ7zf9_-XhI4XqsX7jXlKkHdtS5Vo',
    appId: '1:792474175652:web:2bef2bda28f23f3bc9fe31',
    messagingSenderId: '792474175652',
    projectId: 'gemini-ee839',
    authDomain: 'gemini-ee839.firebaseapp.com',
    storageBucket: 'gemini-ee839.appspot.com',
  );
}
