// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOtt7Ojqu7D4bW7nEz5OftHPOY8V7qOxM',
    appId: '1:1075327583731:web:43c48eeb3cb807c799be86',
    messagingSenderId: '1075327583731',
    projectId: 'wander-6ad0c',
    authDomain: 'wander-6ad0c.firebaseapp.com',
    storageBucket: 'wander-6ad0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQRhrXU-6wUmcYNQ9sroz-pd6JnI8hpk',
    appId: '1:1075327583731:android:514f9951dc1bbd4b99be86',
    messagingSenderId: '1075327583731',
    projectId: 'wander-6ad0c',
    storageBucket: 'wander-6ad0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfu-mzZo5rVDQbH5Y3rMSghdSYUwZwCU8',
    appId: '1:1075327583731:ios:1e9aaf2796c1168799be86',
    messagingSenderId: '1075327583731',
    projectId: 'wander-6ad0c',
    storageBucket: 'wander-6ad0c.appspot.com',
    iosBundleId: 'com.example.wanderFindsGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfu-mzZo5rVDQbH5Y3rMSghdSYUwZwCU8',
    appId: '1:1075327583731:ios:1e9aaf2796c1168799be86',
    messagingSenderId: '1075327583731',
    projectId: 'wander-6ad0c',
    storageBucket: 'wander-6ad0c.appspot.com',
    iosBundleId: 'com.example.wanderFindsGemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOtt7Ojqu7D4bW7nEz5OftHPOY8V7qOxM',
    appId: '1:1075327583731:web:e237e51c49ca2a0499be86',
    messagingSenderId: '1075327583731',
    projectId: 'wander-6ad0c',
    authDomain: 'wander-6ad0c.firebaseapp.com',
    storageBucket: 'wander-6ad0c.appspot.com',
  );
}
